[package]

name = "resos"
version = "0.0.1"
authors = ["Connor Doyle <connor@mesosphere.io>"]

[dependencies]
libc = "*"

[dependencies.protobuf]

git = "https://github.com/stepancheg/rust-protobuf.git"
rev = "d6e80593f38ce47dfa0c4912a3558fa33ee06143"
